common:
  speed:
    slowly: &SLOWLY
      speed: 0.2
      accel: 0.1
      timeout: 10.
    normally: &NORMALLY
      speed: 0.4
      accel: 0.3
      timeout: 6.
    quickly: &QUICKLY
      speed: 0.6
      accel: 0.6
      timeout: 4.

  tolerance:
    small_tolerance: &SMALL_TOLERANCE
      tolerance_joints: [ 0.008, 0.008, 0.008, 0.1, 0.1, 0.01 ]
    normal_tolerance: &NORMAL_TOLERANCE
      tolerance_joints: [ 0.008, 0.008, 0.008, 0.1, 0.1, 0.1 ]
    bigger_tolerance: &BIGGER_TOLERANCE
      tolerance_joints: [ 0.01, 0.01, 0.01, 0.2, 0.2, 0.2 ]
    test_tolerance: &TEST_TOLERANCE
      tolerance_joints: [ 0.04, 0.1, 0.04, 1.0, 1.0, 1.5 ]

  gripper:
    open_gripper: &OPEN_GRIPPER
      state: false
    close_gripper: &CLOSE_GRIPPER
      state: true

  arm:
    home_zero_stone: &HOME_ZERO_STONE
      joints: [0.02, 0.013, 0.007, -1.487, 1.581, -0.194]
      common:
        <<: *NORMALLY
      tolerance:
        <<: *NORMAL_TOLERANCE
    home_one_stone: &HOME_ONE_STONE
      joints: [0.107, 0.013, 0.007, -1.487, 1.581, -0.194]
      common:
        <<: *NORMALLY
      tolerance:
        <<: *NORMAL_TOLERANCE
    home_two_stone: &HOME_TWO_STONE
      joints: [0.309, 0.013, 0.007, -1.487, 1.581, -0.194]
      common:
        <<: *NORMALLY
      tolerance:
        <<: *NORMAL_TOLERANCE
    home_zero_stone_slowly: &HOME_ZERO_STONE_SLOWLY
      joints: [ 0.02, 0.013, 0.007, -1.487, 1.581, -0.194 ]
      common:
        <<: *SLOWLY
      tolerance:
        <<: *NORMAL_TOLERANCE
    home_one_stone_slowly: &HOME_ONE_STONE_SLOWLY
      joints: [ 0.107, 0.013, 0.007, -1.487, 1.581, -0.194 ]
      common:
        <<: *SLOWLY
      tolerance:
        <<: *NORMAL_TOLERANCE
    home_two_stone_slowly: &HOME_TWO_STONE_SLOWLY
      joints: [ 0.309, 0.013, 0.007, -1.487, 1.581, -0.194 ]
      common:
        <<: *SLOWLY
      tolerance:
        <<: *NORMAL_TOLERANCE
    pick_wait:  &PICK_WAIT
      joints: [0.438, 0.027, 0.005, -1.525, 1.616, -0.078]
      common:
        <<: *NORMALLY
      tolerance:
        <<: *BIGGER_TOLERANCE

  gimbal:
    sky_gimbal: &SKY_POS
      frame: gimbal_base
      position: [ 2, 0.15, 0.5 ]
    back_gimbal: &BACK_POS
      frame: gimbal_base
      position: [ -2 ,0.01, 0. ]
    island_gimbal: &ISLAND_POS
      frame: gimbal_base
      position: [ 2 ,0.01, -0.25 ]
    ground_pos: &GROUND_POS
      frame: gimbal_base
      position: [ 2 ,0.01, -0.2 ]
    reversal_pos: &REVERSAL_POS
      frame: gimbal_base
      position: [ 2,0.01, 0.]
    exchange_pos: &EXCHANGE_POS
      frame: gimbal_base
      position: [ 0.01,-3, -1.0 ]

steps_list:
  ################### COMMON STEP####################
  DELETE_SCENE:
    - step: "delete_scene"
  ################### GIMBAL ####################
  SKY_GIMBAL:
    - step: "sky island gimbal"
      gimbal:
        <<: *SKY_POS
  ISLAND_GIMBAL:
    - step: "island gimbal"
      gimbal:
        <<: *ISLAND_POS
  BACK_GIMBAL:
    - step: "back gimbal"
      gimbal:
        <<: *BACK_POS
  GROUND_GIMBAL:
    - step: "ground gimbal"
      gimbal:
        <<: *GROUND_POS
  REVERSAL_GIMBAL:
    - step: "reversal gimbal"
      gimbal:
        <<: *REVERSAL_POS
  EXCHANGE_GIMBAL:
    - step: "exchange gimbal"
      gimbal:
        <<: *EXCHANGE_POS
  ################### GRIPPER ####################
  OPEN_GRIPPER:
    - step: "open gripper"
      gripper:
        <<: *OPEN_GRIPPER

  CLOSE_GRIPPER:
    - step: "close gripper"
      gripper:
        <<: *CLOSE_GRIPPER
  ################### CHASSIS ####################
  CHASSIS_FORWARD:
    - step: "forward"
      chassis:
        frame: base_link
        position: [ 0.3, 0. ]
        yaw: 0.0
        chassis_tolerance_position_: 0.025
        chassis_tolerance_angular_: 0.1

  CHASSIS_BACKWARD:
    - step: "backward"
      chassis:
        frame: base_link
        position: [ -0.08, 0. ]
        yaw: 0.0
        chassis_tolerance_position_: 0.04
        chassis_tolerance_angular_: 0.2

  CHASSIS_LEFT:
    - step: "left"
      chassis:
        frame: base_link
        position: [ 0., 0.5 ]
        yaw: 0.0
        chassis_tolerance_position_: 0.1
        chassis_tolerance_angular_: 0.01

  CHASSIS_RIGHT:
    - step: "right"
      chassis:
        frame: base_link
        position: [ 0., -0.5 ]
        yaw: 0.0
        chassis_tolerance_position_: 0.1
        chassis_tolerance_angular_: 0.01

  CHASSIS_ROTATE:
    - step: "rotate"
      chassis:
        frame: base_link
        position: [ 0., 0. ]
        yaw: 3.14
        chassis_tolerance_position_: 1.
        chassis_tolerance_angular_: 0.01

  ################### CHASSIS ####################

  ################### HOME ####################

  HOME_ZERO_STONE:
    - step: "home with no stone"
      arm:
        <<: *HOME_ZERO_STONE
  HOME_ONE_STONE:
    - step: "home with one stone"
      arm:
        <<: *HOME_ONE_STONE
  HOME_TWO_STONE:
    - step: "home with two stone"
      arm:
        <<: *HOME_TWO_STONE


  ################### GROUND ####################
  GROUND_STONE:
    - step: "change gripper state"
      gripper:
        <<: *OPEN_GRIPPER
    - step: "get ground stone"
      arm:
        joints: [-0.004100, 0.013219784447105642, 0.006857136886879611, -0.0987931242925928, -0.00996003076049834, 0.076470]
        common:
          <<: *NORMALLY
        tolerance:
          <<: *BIGGER_TOLERANCE
  GROUND_STONE0:
    - step: "arm wait state"
      arm:
        <<: *HOME_ONE_STONE_SLOWLY

  ################### EXCHANGE ####################
  EXCHANGE_WAIT:
    - step: "move to exchange wait state"
      arm:
        joints: [0.0679, 0.03605, 0.0066, -1.6025, 0.0131, 0.0785]
        common:
          <<: *NORMALLY
        tolerance:
          <<: *BIGGER_TOLERANCE
  ###################    SKY_BIG_ISLAND    ####################
  SKY_BIG_ISLAND0:
    - step: "arm wait state"
      arm:
        <<: *PICK_WAIT
  SKY_BIG_ISLAND00:
    - step: "move to stone down"
      arm:
        joints: [0.434, 0.2830, 0.0057, -1.657, -0.059, 0.0110]
        common:
          <<: *NORMALLY
        tolerance:
          <<: *BIGGER_TOLERANCE
    - step: "change gripper state"
      gripper:
        <<: *OPEN_GRIPPER
  SKY_BIG_ISLAND000:
    - step: "arm back"
      arm:
        <<: *PICK_WAIT
    ###################    BIG_ISLAND    ####################
    ###################    MID    ################
  BIG_ISLAND0:
    - step: "arm wait"
      arm:
        <<: *PICK_WAIT
  BIG_ISLAND00:
    - step: "add scenes"
      scene_name: MID_BIG_ISLAND
    - step: "arm ready to get"
      arm:
        joints: [0.431, 0.310, 0.005, -1.693, -0.054, 3.208]
        common:
          <<: *NORMALLY
        tolerance:
          <<: *NORMAL_TOLERANCE
    - step: "change gripper state"
      gripper:
          <<: *OPEN_GRIPPER
    - step: "delete_scene"
  BIG_ISLAND000:
    - step: "get stone"
      arm:
        joints: [0.299, 0.310, 0.005, -1.693, -0.054, 3.208]
        common:
          <<: *NORMALLY
        tolerance:
          <<: *NORMAL_TOLERANCE
    - step: "up stone"
      arm:
        joints: [0.435, 0.310, 0.005, -1.693, -0.054, 3.208]
        common:
          <<: *NORMALLY
        tolerance:
          <<: *NORMAL_TOLERANCE
    - step: "reversal stone"
      arm:
        joints: [0.433, 0.310, 0.005, -1.693, -0.054, 0.014]
        common:
          <<: *SLOWLY
        tolerance:
          <<: *BIGGER_TOLERANCE
    - step: "arm wait state"
      arm:
        <<: *PICK_WAIT
  ###################    SMALL_ISLAND    ####################
  LF_SMALL_ISLAND0:
    - step: "arm wait"
      arm:
        <<: *PICK_WAIT
  TEST_SMALL_ISLAND00:
    - step: "add scenes"
      scene_name: MID_SMALL_ISLAND
    - step: "arm ready to get stone"
      arm:
        joints:  [ 0.40, 0.031, 0.2714, -1.518, -0.043, 3.217387077106941 ]
        common:
          <<: *NORMALLY
        tolerance:
          <<: *TEST_TOLERANCE

  NORMALLY_SMALL_ISLAND00:
    - step: "add scenes"
      scene_name: MID_SMALL_ISLAND
    - step: "arm ready to get stone"
      arm:
        joints: [ 0.40, 0.031, 0.2714, -1.518, -0.043, 3.217387077106941 ]
        common:
          <<: *NORMALLY
        tolerance:
          <<: *NORMAL_TOLERANCE
  LF_SMALL_ISLAND00:
    - step: "arm ready to get stone"
      arm:
        joints: [ 0.40, 0.031, 0.2714, -1.518, -0.043, 3.217387077106941 ]
        common:
          <<: *NORMALLY
        tolerance:
          <<: *NORMAL_TOLERANCE
    - step: "change gripper state"
      gripper:
        <<: *OPEN_GRIPPER
    - step: "move arm down to gain stone"
      arm:
        joints: [ 0.279, 0.031, 0.2714, -1.518, -0.043, 3.217387077106941 ]
        common:
          <<: *QUICKLY
        tolerance:
          <<: *BIGGER_TOLERANCE
    - step: "move arm up"
      arm:
        joints: [ 0.458, 0.031, 0.2012, -1.518, -0.043, 3.217387077106941 ]
        common:
          <<: *QUICKLY
        tolerance:
          <<: *BIGGER_TOLERANCE
    - step: "reversal stone"
      arm:
        joints: [ 0.452, 0.0316, 0.2012, -1.436, 0.011, 1.0 ]
        common:
          <<: *SLOWLY
        tolerance:
          <<: *BIGGER_TOLERANCE
    - step: "arm wait"
      arm:
        <<: *PICK_WAIT
    ###################    MID    ################
  SMALL_ISLAND0:
    - step: "arm wait"
      arm:
        <<: *PICK_WAIT
    - step: "change gripper state"
      gripper:
        <<: *OPEN_GRIPPER
  SMALL_ISLAND00:
    - step: "add scenes"
      scene_name: MID_SMALL_ISLAND
    - step: "arm ready to get stone"
      arm:
        joints: [0.4234533056100423, 0.03084413880417841, 0.00879305699769145, -1.5101404974370372, 0.004258877900558122, 3.217387077106941]
        common:
          <<: *NORMALLY
        tolerance:
          <<: *BIGGER_TOLERANCE
    - step: "change gripper state"
      gripper:
        <<: *OPEN_GRIPPER
    - step: "delete_scene"
  SMALL_ISLAND000:
    - step: "arm get stone"
      arm:
        joints: [0.290, 0.031, 0.009, -1.522, -0.001, 3.217387077106941]
        common:
          <<: *QUICKLY
        tolerance:
          <<: *BIGGER_TOLERANCE
    - step: "arm up stone"
      arm:
        joints: [0.435, 0.031, -0.10, -1.4992037839, 0.008332834876478845, 3.2080808812697885]
        common:
          <<: *QUICKLY
        tolerance:
          <<: *BIGGER_TOLERANCE
    - step: "reversal stone"
      arm:
        joints: [ 0.438, 0.031, -0.10, -1.476, 0.001, 1.0 ]
        common:
          <<: *SLOWLY
        tolerance:
          <<: *BIGGER_TOLERANCE
    - step: "arm back"
      arm:
        <<: *PICK_WAIT

    ###################    RT    ################
  RT_SMALL_ISLAND0:
    - step: "arm wait"
      arm:
        <<: *PICK_WAIT
  RT_SMALL_ISLAND00:
    - step: "arm ready"
      arm:
        joints: [0.406, 0.031, -0.243350, -1.509, -0.008, 3.284460]
        common:
          <<: *NORMALLY
        tolerance:
          <<: *NORMAL_TOLERANCE
    - step: "change gripper state"
      gripper:
          <<: *OPEN_GRIPPER
    - step: "arm get stone"
      arm:
        joints: [ 0.279, 0.031, -0.243350, -1.509, -0.008, 3.284460 ]
        common:
          <<: *QUICKLY
        tolerance:
          <<: *BIGGER_TOLERANCE
    - step: "arm up stone"
      arm:
        joints: [ 0.453, 0.031, -0.280050, -1.460, -0.027, 3.284460 ]
        common:
          <<: *QUICKLY
        tolerance:
          <<: *BIGGER_TOLERANCE
    - step: "reversal stone"
      arm:
        joints:  [0.453, 0.031, -0.288, -1.460, -0.027, 1.0]
        common:
          <<: *NORMALLY
        tolerance:
          <<: *BIGGER_TOLERANCE
    - step: "arm back"
      arm:
        <<: *PICK_WAIT
      ###################    SMALL_ISLAND    ####################
      ###################    STORE    ####################
  STORE_WHEN_ZERO_STONE0:
    - step: "open gripper"
      gripper:
        <<: *OPEN_GRIPPER
    - step: "move joint1 and 3"
      arm:
        joints: [ 0.107, 0.02, -0.225, -1.487, 1.581, 0.007 ]
        common:
          <<: *NORMALLY
        tolerance:
          <<: *BIGGER_TOLERANCE

  STORE_WHEN_ZERO_STONE00:
    - step: "move joint6"
      arm:
        joints: [ 0.107, -0.03, -0.225, -1.487, 1.581, 1.969710 ]
        common:
          <<: *NORMALLY
        tolerance:
          <<: *BIGGER_TOLERANCE
    - step: "close gripper"
      gripper:
        <<: *CLOSE_GRIPPER


  STORE_WHEN_ZERO_STONE000:
    - step: "move joint6"
      arm:
        <<: *HOME_ONE_STONE

  STORE_WHEN_ONE_STONE0:
    - step: "open gripper"
      gripper:
        <<: *OPEN_GRIPPER
    - step: "move joint1 and 3"
      arm:
        joints: [ 0.309, 0.02, -0.225, -1.487, 1.581, 0.007  ]
        common:
          <<: *NORMALLY
        tolerance:
          <<: *BIGGER_TOLERANCE

  STORE_WHEN_ONE_STONE00:
    - step: "move joint6"
      arm:
        joints: [ 0.309, -0.03, -0.225, -1.487, 1.581, 1.969710 ]
        common:
          <<: *NORMALLY
        tolerance:
          <<: *BIGGER_TOLERANCE
    - step: "close gripper"
      gripper:
        <<: *CLOSE_GRIPPER

  STORE_WHEN_ONE_STONE000:
    - step: "home two stone"
      arm:
        <<: *HOME_TWO_STONE
      ###################   TAKE   ####################
  TAKE_WHEN_ONE_STONE0:
    - step: "open gripper"
      gripper:
        <<: *OPEN_GRIPPER
    - step: "move joint1 and 3 and 6"
      arm:
        joints: [ 0.084, 0.10, -0.276, -1.487, 1.581, 1.601 ]
        common:
          <<: *NORMALLY
        tolerance:
          <<: *BIGGER_TOLERANCE

  TAKE_WHEN_ONE_STONE00:
    - step: "move joint2 to get stone"
      arm:
        joints: [ 0.084, -0.03, -0.266, -1.541, 1.656, 1.601 ]
        common:
          <<: *NORMALLY
        tolerance:
          <<: *BIGGER_TOLERANCE

  TAKE_WHEN_ONE_STONE000:
    - step: "move joint6"
      arm:
        joints: [ 0.08264350643170443, 0., -0.266, -1.5407632953407409, 1.656, -0.0031957346223543404 ]
        common:
          <<: *SLOWLY
        tolerance:
          <<: *BIGGER_TOLERANCE
    - step: "home with no stone"
      arm:
        <<: *HOME_ZERO_STONE

  TAKE_WHEN_ONE_STONE0000:
    - step: "home with no stone"
      arm:
        <<: *HOME_ZERO_STONE

  TAKE_WHEN_TWO_STONE0:
    - step: "open gripper"
      gripper:
        <<: *OPEN_GRIPPER
    - step: "move joint1 and 3 and 6"
      arm:
        joints: [ 0.276, 0.10, -0.276, -1.487, 1.581, 1.601  ]
        common:
          <<: *NORMALLY
        tolerance:
          <<: *BIGGER_TOLERANCE

  TAKE_WHEN_TWO_STONE00:
    - step: "move joint6 to get stone"
      arm:
        joints: [ 0.276, -0.03, -0.266, -1.541, 1.656, 1.601 ]
        common:
          <<: *NORMALLY
        tolerance:
          <<: *BIGGER_TOLERANCE

  TAKE_WHEN_TWO_STONE000:
    - step: "move joint6"
      arm:
        joints: [ 0.276, 0., -0.266, -1.5407632953407409, 1.656, -0.0031957346223543404  ]
        common:
          <<: *SLOWLY
        tolerance:
          <<: *BIGGER_TOLERANCE
    - step: "home with no stone"
      arm:
        <<: *HOME_ONE_STONE

  TAKE_WHEN_TWO_STONE0000:
    - step: "home with no stone"
      arm:
        <<: *HOME_ONE_STONE
